version: '3.8'
services:
  nginx:
    container_name: web
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/usr/share/nginx/html
      - ./docker/nginx/:/etc/nginx/conf.d
      - ./docker/data/nginx/cert:/usr/local/nginx/ssl
      - ./docker/data/nginx/logs:/var/log/nginx
    depends_on:
      - php70
      - php82
    networks:
      - projeto_docker

  php70:
    container_name: php70
    build: 
      context: .
      dockerfile: ./docker/php/7.0/Dockerfile
    ports:
      - 9000:9001
    volumes:
      -  ./www:/usr/share/nginx/html   
    networks:
      - projeto_docker

  php82:
    container_name: php82
    build: 
      context: .
      dockerfile: ./docker/php/8.2/Dockerfile
    expose:
      - "9000"
    volumes:
      - ./www:/usr/share/nginx/html
    networks:
      - projeto_docker

  database-mysql:
    container_name: mysql
    image: mysql
    restart: always
    volumes: 
      - ./docker/database/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: docker
      MYSQL_ROOT_PASSWORD: 123123
    ports:
      - 3306:3306
    networks:
      - projeto_docker
networks: 
    projeto_docker:
      driver: bridge
  